#!/bin/env python3

import os
from sys import argv
import subprocess

shfile="""#!/bin/bash

#SBATCH --nodes=1 
#SBATCH --ntasks={0}
#SBATCH --mem={1}GB
#SBATCH -t {2}:{3}:00
{4}

export TEMPORARY_DIR=/tmp/$SLURM_JOB_ID
export MACHINEFILE=`/fslapps/fslutils/generate_pbs_nodefile`
export SCRATCH_DIR="$TEMPORARY_DIR/temporary_files"
export JOB_NAME={5}
export JOB_SOURCE_DIR="$SLURM_SUBMIT_DIR"

echo "---------------------------------------------------------"
echo "Gaussian09 Job Output Information:"
echo "---------------------------------------------------------"
echo "Current node:"
cat "$MACHINEFILE"
echo "---------------------------------------------------------"
echo "JOB START TIME: $(date)"

module load g09

/fslapps/gaussian09/B.01/EM64T/g09/g09 < "{5}.com" > "{5}.log"

echo "---------------------------------------------------------"
echo "JOB END TIME: $(date)
echo "---------------------------------------------------------"
exit EXIT_CODE=$?
#echo $EXIT_CODE
"""

#Gathering Inputs
INPUT=[i for i in argv[1:]]

def ReadInput(INPUT):
	test=False
	if INPUT[-1] == "-t":
		test=True
	cpus=str(INPUT[0])
	mem=str(INPUT[1])
	hours=str(INPUT[2]).zfill(2)
	minutes=str(INPUT[3]).zfill(2)
	return cpus,mem,hours,minutes,test

options=list(ReadInput(INPUT))
if options[-1]==False:
	test=""
if options[-1]==True:
	test="#SBATCH --qos=test"

###Finding the input file in the directory###
FILES=[i[:i.find('.')] for i in os.listdir(os.getcwd()) if i.endswith(".com")]

###Adding the file name to the options list###
options[-1]=test
options+=[FILES[0]]

submit=shfile.format(*options)

###Writing to .sh template###
with open('{}.sh'.format(options[5]),'w') as SH:
	SH.write(submit)

###Prompt for submission###
ready=("""
Are you ready to submit these jobs?: 
----------------------------
CPUS: {0}
Memory: {1}
Time: {2}:{3}:00
----------------------------""").format(*options)
print(ready)
status=input("Response (y/n):")

###Actual Submission###
if status=="y":
	os.system("sbatch {}.sh".format(options[5]))
else:
	print("The Job Was Not Submitted")

